plugins:
  unwise_authentication_enabled:
    default: true
    client: true
users:
  min_password_length:
    client: true
    min: 1
    default: 1
    max: 500
  min_admin_password_length:
    client: true
    min: 1
    default: 1
    max: 500
  block_common_passwords: false 
